-- ===================================
-- MISE À JOUR DES HÉBERGEMENTS AVEC IMAGES
-- ===================================

-- Supprimer les données existantes pour les remplacer par les nouvelles
DELETE FROM accommodations;

-- Insérer les données complètes avec images
INSERT INTO accommodations (
    id, name, slug, description, excerpt, type, capacity, bedrooms, beds_description,
    address, village, phone, email, website, facebook, features, featured_image, status
) VALUES 
(
    'la-loge-bed-breakfast',
    'La Loge Bed & Breakfast',
    'la-loge-bed-breakfast-vaudignies',
    'Séjournez dans un appartement chaleureux au cœur du hameau de Vaudignies. Profitez d''un cadre cosy et lumineux avec option petit-déjeuner, idéal pour découvrir Chièvres et ses villages environnants.',
    'Appartement chaleureux au cœur de Vaudignies avec option petit-déjeuner',
    'bed_breakfast',
    4,
    2,
    '2 à 4 personnes',
    'Rue de Ladeuze, 1 – Vaudignies',
    'Vaudignies',
    '0472 65 32 01',
    'laloge@outlook.be',
    NULL,
    'https://www.facebook.com/laloge',
    ARRAY['Accueil personnalisé et convivial', 'Appartement lumineux et confortable', 'Option petit-déjeuner inclus', 'Proximité des balades et circuits touristiques'],
    'https://picsum.photos/id/1001/600/400',
    'published'
),
(
    'au-sentier-chauchaut',
    'Au sentier Chauchaut',
    'au-sentier-chauchaut-chievres',
    'Séjournez dans une ancienne ferme du XIXᵉ siècle rénovée avec soin pour allier confort moderne et charme authentique. Profitez d''un moment de calme et de l''accueil chaleureux de M. et Mme Ost‑Nasdrovisky.',
    'Ancienne ferme du XIXᵉ siècle rénovée avec charme authentique',
    'bed_breakfast',
    5,
    2,
    '3 à 5 personnes',
    'Sentier Chauchaut, 1',
    'Chièvres',
    '0473 96 11 94',
    'ostchr1968@gmail.com',
    'https://www.ausentierchauchaut.com',
    NULL,
    ARRAY['Maison chargée d''histoire, atmosphère authentique', 'Chambres confortables', 'Proximité des balades, du patrimoine et des circuits touristiques', 'À deux pas de Pairi Daiza et des villes d''art comme Mons et Tournai'],
    'https://picsum.photos/id/1002/600/400',
    'published'
),
(
    'la-maison-dacote',
    'La Maison d''à côté',
    'la-maison-dacote-tongre-saint-martin',
    'Partie d''une ancienne ferme rénovée datant de 1872, ce gîte 3 épis allie calme et confort au cœur de la campagne chiévroise. Idéal pour les familles ou petits groupes, il offre des moments de repos et des découvertes naturelles à pied ou à vélo, sur le GR 121 ou le RAVeL à proximité.',
    'Gîte 3 épis dans une ancienne ferme de 1872, calme et confort',
    'gite',
    5,
    2,
    '5 personnes (2 chambres)',
    'Rue Emile Daubechies, 4',
    'Tongre-Saint-Martin',
    '0474 78 71 99',
    'winieckimic@gmail.com',
    'https://www.lamaisondacote.be',
    NULL,
    ARRAY['Gîte spacieux et confortable pour 5 personnes', 'Tranquillité et cadre champêtre', 'Balades à pied ou à vélo sur le GR 121 et le RAVeL', 'À quelques minutes en voiture du célèbre Parc Pairi Daiza'],
    'https://picsum.photos/id/1003/600/400',
    'published'
),
(
    'au-champ-du-bouillon',
    'Au Champ du Bouillon',
    'au-champ-du-bouillon-tongre-notre-dame',
    'Séjournez dans ce gîte tout confort, parfait pour une escapade tranquille en couple ou en petit groupe. Profitez d''un cadre paisible et d''un espace bien-être privatif pour un séjour détente au cœur de la campagne chiévroise.',
    'Gîte tout confort avec espace bien-être privatif',
    'gite',
    4,
    2,
    '2 à 4 personnes',
    'Rue de la Ladrerie, 12',
    'Tongre-Notre-Dame',
    '0498 07 00 85',
    'rogejoh@hotmail.com',
    NULL,
    'https://www.facebook.com/profile.php?id=100064563347866',
    ARRAY['Confort moderne dans un cadre rural', 'Espace bien-être privatif pour se relaxer', 'Proximité des balades et circuits touristiques', 'Accueil chaleureux et personnalisé'],
    'https://picsum.photos/id/1004/600/400',
    'published'
),
(
    'les-greniers-du-moulin',
    'Les Greniers du Moulin',
    'les-greniers-du-moulin-grosage',
    'Séjournez dans ce gîte à la ferme et découvrez l''authenticité de la campagne chiévroise. Avec un élevage de vaches Jersey sur place et un petit magasin fermier ouvert le samedi, vous pourrez profiter d''un cadre naturel et goûter aux produits locaux. Idéal pour les familles ou groupes d''amis, ce gîte spacieux est parfait pour se détendre et explorer les environs.',
    'Gîte à la ferme avec élevage de vaches Jersey et magasin fermier',
    'gite',
    8,
    3,
    '8 personnes (3 chambres, 7 lits)',
    'Rue des Héros de Roumont, 26',
    'Grosage',
    '0478 45 94 19',
    'lafermedumoulin@skynet.be',
    NULL,
    'https://www.facebook.com/profile.php?id=61552163278202',
    ARRAY['Gîte spacieux pour 8 personnes', 'Ambiance authentique dans une ferme bio', 'Proximité des sentiers de randonnée et balades à vélo', 'Magasin à la ferme avec produits locaux (uniquement le samedi)'],
    'https://picsum.photos/id/1005/600/400',
    'published'
),
(
    'levasion-yacht',
    'L''Évasion',
    'levasion-yacht-ladeuze',
    'Vivez une expérience unique en séjournant sur un yacht amarré à Ladeuze. Ce gîte insolite combine confort et originalité pour un séjour inoubliable au fil de l''eau, idéal pour les familles ou petits groupes.',
    'Séjour insolite sur un yacht amarré à Ladeuze',
    'unusual',
    6,
    3,
    '6 personnes (3 chambres : 2 lits doubles, 1 lit superposé)',
    'Rue Grande Drève',
    'Ladeuze',
    '0491 86 58 09',
    'evasionyacht@hotmail.com',
    NULL,
    'https://www.facebook.com/evasionyacht',
    ARRAY['Séjour insolite sur un yacht au calme', '3 chambres confortables pour 6 personnes', 'Cadre charmant au bord de l''eau', 'Proximité des balades le long du RAVel'],
    'https://picsum.photos/id/1006/600/400',
    'published'
),
(
    'moulin-du-domissart',
    'Moulin du Domissart',
    'moulin-du-domissart-grosage',
    'Bienvenue chez Aurore et Thomas, au Moulin du Domissart, un ancien moulin à eau du XVIᵉ siècle, restauré et transformé en 4 gîtes. Abritant d''anciennes machines du moulin, vous aurez la sensation de séjourner dans un musée vivant. Plus qu''un hébergement, c''est un lieu apaisant et convivial, idéal pour les familles, groupes d''amis ou team buildings professionnels. Bercé par le ruissellement de l''eau, le Moulin du Domissart offre un cadre parfait pour promenades, escapades nature et découvertes de la campagne chiévroise. Un espace bien-être et un barbecue à disposition sont également disponibles pour des moments de détente et de convivialité.',
    'Ancien moulin à eau du XVIᵉ siècle transformé en 4 gîtes avec espace bien-être',
    'gite',
    24,
    8,
    '4 gîtes, jusqu''à 24 personnes',
    'Rue Puits à Leval, 27',
    'Grosage',
    '0477 13 22 99',
    'info@moulin-a-eau.be',
    'https://www.moulin-a-eau.be/',
    NULL,
    ARRAY['Cadre unique dans un moulin à eau historique du XVIᵉ siècle', 'Capacité totale de 24 personnes répartie sur 4 gîtes', 'Atmosphère apaisante, parfaite pour se ressourcer', 'Proximité des balades, circuits touristiques et villages voisins', 'Espace Wellness', 'Ménage inclus'],
    'https://picsum.photos/id/1007/600/400',
    'published'
),
(
    'chez-les-kikis',
    'Chez les Kikis',
    'chez-les-kikis-chievres',
    'Ce gîte rural tout confort, situé en contrebas de la Tour de Gavre et de l''église St Martin de Chièvres, vous offre une escapade reposante au cœur de la ville. Idéal pour un couple ou une petite famille, il est également à proximité de la Casa des Aviateurs, pour profiter de paddle, laser game et mini foot.',
    'Gîte rural au pied des monuments historiques de Chièvres',
    'gite',
    3,
    1,
    '2 adultes + 1 adulte dans canapé-lit ou 2 petits enfants',
    'Rue Royale, 28C',
    'Chièvres',
    '068 65 78 18',
    'chezleskiki@gmail.com',
    NULL,
    NULL,
    ARRAY['Gîte cosy et confortable pour 2 à 3 personnes', 'Cadre calme, au pied des monuments historiques de Chièvres', 'Proximité des activités sportives et ludiques de la Casa des Aviateurs', 'Idéal pour une escapade familiale ou reposante'],
    'https://picsum.photos/id/1008/600/400',
    'published'
),
(
    'on-dirait-le-sud',
    'On dirait le sud…',
    'on-dirait-le-sud-ladeuze',
    'Profitez d''un séjour convivial et reposant dans cette chambre d''hôtes chaleureuse. Idéal pour familles ou petits groupes, ce lieu charmant vous permettra de découvrir Ladeuze et la campagne chiévroise en toute tranquillité.',
    'Chambre d''hôtes chaleureuse avec piscine extérieure',
    'bed_breakfast',
    4,
    2,
    '4 personnes (2 chambres : "Tintin" avec 2 lits simples, "Doux Repos" avec 1 lit double)',
    'Rue de la Gare, 11B',
    'Ladeuze',
    '0477 99 59 27',
    'duquesnereal@hotmail.be',
    NULL,
    NULL,
    ARRAY['2 chambres confortables pour 4 personnes', 'Piscine extérieure pour se rafraîchir', 'Petit déjeuner fabuleux préparé par le chef Réal', 'Ambiance chaleureuse et accueillante', 'Proximité des balades, circuits touristiques et villages voisins'],
    'https://picsum.photos/id/1009/600/400',
    'published'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    excerpt = EXCLUDED.excerpt,
    type = EXCLUDED.type,
    capacity = EXCLUDED.capacity,
    bedrooms = EXCLUDED.bedrooms,
    beds_description = EXCLUDED.beds_description,
    address = EXCLUDED.address,
    village = EXCLUDED.village,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    website = EXCLUDED.website,
    facebook = EXCLUDED.facebook,
    features = EXCLUDED.features,
    featured_image = EXCLUDED.featured_image,
    status = EXCLUDED.status,
    updated_at = NOW();

-- Vérification finale
SELECT 
    COUNT(*) as total_accommodations,
    COUNT(CASE WHEN status = 'published' THEN 1 END) as published,
    COUNT(CASE WHEN featured_image IS NOT NULL THEN 1 END) as with_images,
    COUNT(CASE WHEN type = 'gite' THEN 1 END) as gites,
    COUNT(CASE WHEN type = 'bed_breakfast' THEN 1 END) as bed_breakfasts,
    COUNT(CASE WHEN type = 'unusual' THEN 1 END) as unusual
FROM accommodations;